#!/bin/sh
set -a
. ./.env
set +a

case "$1" in
    sql)
        sqlite3 threats.db "SELECT * FROM reports ORDER BY score DESC;"
        ;;
    docker)
		touch threats.db
        docker run \
            -e WAYLAND_DISPLAY="$WAYLAND_DISPLAY" \
            -e XDG_RUNTIME_DIR=/tmp \
            --env-file .env \
            -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY" \
            -v "$(pwd)/threats.db:/app/threats.db" \
            threat-intel /app/threat-intel
        ;;    
    gcc)
        gcc main.c api.c db.c threadpool.c -o threat-intel \
            $(pkg-config --cflags --libs gtk+-3.0) \
            -lcurl -lcjson -lsqlite3 && ./threat-intel
        ;;
    cmake)
	    mkdir -p build && cd build && cmake .. && make && cd .. && ./build/threat-intel
    	;;
    *)
        echo "Usage: run {sql|docker|gcc|cmake}"
        exit 1
        ;;
esac
